{
 "title": "Autonomi Arb Wallet Exporter v1.1",
 "description": "A basic dashboard to query the autonomi exporter",
 "tags": [
  "docker",
  "autonomi",
  "ant_exporter",
  "python"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "wallet",
    "label": "wallet",
    "query": {
     "query": "label_values({__name__=~\"token_balance_.*\"},wallet)"
    }
   },
   {
    "name": "symbol",
    "label": "symbol",
    "query": {
     "query": "label_values({__name__=~\"token_balance_.*\"},symbol)"
    }
   },
   {
    "name": "chain",
    "label": "chain",
    "query": {
     "query": "label_values({__name__=~\"token_balance_.*\"},chain)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values({__name__=~\"token_balance_.*\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wallet",
   "type": "stat",
   "description": "Number of wallets seen in the configuration",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (wallet) ({__name__=~\"token_balance_.*\"}))",
     "legendFormat": "{{wallet}}"
    }
   ]
  },
  {
   "title": "Symbol",
   "type": "stat",
   "description": "Number of token symbols seen in the configuration",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (symbol) ({__name__=~\"token_balance_.*\"}))",
     "legendFormat": "{{Symbol}}"
    }
   ]
  },
  {
   "title": "Chains",
   "type": "stat",
   "description": "Number of Chains seen in the configuration",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (chain) ({__name__=~\"token_balance_.*\"}))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Top Wallet",
   "type": "stat",
   "description": "Wallet with biggest change in time_period",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum by (wallet, symbol, chain) (\r\n  increase({__name__=~\"token_balance_.*\", symbol=~\".*\", chain=~\".*\"}[$__range])\r\n))\r\n",
     "legendFormat": "{{wallet}}"
    }
   ]
  },
  {
   "title": "Token Balances",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"token_balance_.*\", wallet=~\"$wallet\", symbol=~\"$symbol\", chain=~\"$chain\", name=~\"$name\"}",
     "legendFormat": "wallet: {{wallet}} | name: {{name}}"
    }
   ]
  }
 ]
}